version: '3.1'
services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: yuki
      POSTGRES_PASSWORD: 1
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
